const data = {
  products: [
    {
      _id: '1',
      name: 'Stylistic flame',
      category: 'Flames',
      slug: 'styled-flames',
      image: 'images/p1.jpg',
      price: 940,
      inStock: 94,
      brand: 'planMbrand',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Stylistic gem',
      category: 'Gems',
      slug: 'styled-gems',
      image: 'images/p2.jpg',
      price: 440,
      inStock: 9,
      brand: 'planMbrand_sub',
      rating: 3.5,
      numReviews: 7,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Quartz flame',
      category: 'Flames',
      slug: 'quartz-flame',
      image: 'images/p3.jpg',
      price: 550,
      inStock: 4,
      brand: 'planMbrand',
      rating: 4,
      numReviews: 9,
      description: 'high quality product of course',
    },
    {
      _id: '4',
      name: 'Titanium blue flame',
      category: 'Flames',
      slug: 'blue-flames',
      image: 'images/p4.jpg',
      price: 980,
      inStock: 0,
      brand: 'planMbrand_sub',
      rating: 5,
      numReviews: 14,
      description: 'the smithing of these flames, oh boii',
    },
    {
      _id: '5',
      name: 'Jurassic coral',
      category: 'Corals',
      slug: 'jurassic-coral',
      image: 'images/p5.jpg',
      price: 1180,
      inStock: 3,
      brand: 'planMbrand',
      rating: 4.5,
      numReviews: 24,
      description: 'oh men this shit is legit, where do we even get this',
    },
    {
      _id: '6',
      name: 'Mesozoic coral',
      category: 'Corals',
      image: 'images/p6.jpg',
      slug: 'mesozoic-coral',
      price: 1470,
      inStock: 2,
      brand: 'planMbrand',
      rating: 5,
      numReviews: 47,
      description: 'LAST STOCK I MEAN OMG WHAT ARE THESE',
    },
  ],
};

export default data;
